### ISSUE TITLE
Getting a 404 page not found instead of picture. 

### ISSUE THREAD

**Issue by margotbarranco** [uc-cfss/Discussion#162] opened 2021-01-16 01:32 UTC
I included a picture in homework 01 and it worked fine when I was looking at the preview in R Studio. However, I just checked my work after having submitted it on GitHub and now the picture has been replaced by a link that leads to a 404 page not found. 
The command I used for the picture is 

![text] (photo.png)  

with photo.npg uploaded in the "files" in the R Studio Server (same file where the README.md is saved).

**Comment by fdicera** [comment] 2021-01-16 01:55
Did you commit and push the photo file as well? If not, your photo.png file doesn't exist in your repository on GitHub yet (even though it's there in R Studio), so you'll need to commit and push it first in order to see the image on GitHub.

**Comment by margotbarranco** [comment] 2021-01-16 03:13
Okay I didn't think of that, I think it worked now! Thank you so much! Could you tell me if you can see it too ? I just want to make sure!

**Comment by fdicera** [comment] 2021-01-16 04:08
I can see it!

**Comment by StephenYang866** [comment] 2021-01-16 04:44
I committed and pushed my image file and it shows also in my repository on Github. But rather than the image I can only see my code like ![Big Data](image/big data.jpg) on Github. Whats wrong?

**Comment by bensoltoff** [comment] 2021-01-16 12:34
You have a space in the file name. Rename the file using a hyphen then change the readme to the new filename. We'll talk about the importance of file naming and styling in week 5

**Comment by StephenYang866** [comment] 2021-01-16 18:21
Thanks Professor, the problem is solved!

**Closed as completed** 2021-11-04 17:08 UTC
